pipeline{
    agent any
    tools{
        jdk 'jdk17'
        nodejs 'node23'
    }
    environment {
        SCANNER_HOME = tool'sonar-scanner'
        
        
    }
    
    stages{
        
        stage("Clean"){
            steps{
                cleanWs()
            }
        }
        
        stage("Checkout from Git"){
            steps{
                git branch: 'main', url: 'https://github.com/harshal019/bms-devops-platform.git'
                sh 'ls -la'
            }
        }


        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.projectName=BMS \
                    -Dsonar.projectKey=BMS
                    '''
                }
            }
}

         
        stage("Quality Gate"){
             steps{
                 script {
                waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'   
                 }  
             }
         }
    
        stage('Install Dependencies') {
            steps {
                dir('bookmyshow-app') {
                     sh '''
                        ls -la
                        if [ -f package.json ]; then
                            rm -rf node_modules package-lock.json 
                            npm install 
                        else
                            echo "Error: package.json not found in bookmyshow-app!"
                            exit 1
                        fi
                    '''
               
                }
            }
    }
        stage('OWASP FS Scan') {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit',
                odcInstallation: 'DP-Check'
                dependencyCheckPublisher (pattern: '**/dependency-check-report.xml')
            }
}

        
        stage('Trivy FS Scan') {
         steps {
            sh 'trivy fs . > trivyfs.txt'
         }
        }
        
        stage('Docker Build & Push') {
            steps{
                script{
                    withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
                    sh '''
                     echo "Building Docker image..."
                     docker build --no-cache -t harshalg01/bms-app:latest -f  docker/Dockerfile bookmyshow-app
                     
                     echo "Pushing Docker image to registry..."
                     docker push harshalg01/bms-app:latest
                     '''
                    }
                }
            }
        }
        
        stage('Deploy to Container') {
             steps {
                 sh '''
                 echo "Stopping and removing old container..."
                 docker stop bms || true
                 docker rm bms || true
                 
                 docker run -d --restart=always --name bms -p 3000:80 harshalg01/bms-app:latest
                 
                 docker ps -a
                 
                 sleep 5 
                 docker logs bms
                 '''
             }
            
        }
}


 post {
     always {
         emailext attachLog: true,
         subject: "${currentBuild.result}",
         body: "Project: ${env.JOB_NAME}<br/>" +
             "Build Number: ${env.BUILD_NUMBER}<br/>" +
             "URL: ${env.BUILD_URL}<br/>",
         to: 'harshaldgharat01@gmail.com',
         attachmentsPattern: 'trivyfs.txt,trivyimage.txt'
     }
 }

        
        
        
}